class City {
  int? id; // Nullable, because the ID will be auto-generated by the database
  String name;

  // Constructor to create a City object directly with a name
  City({required this.name});
  // Constructor to create a City from a Map (e.g., from a database row)
  City.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'];

  // Method to convert a City object back to a Map (useful for inserting/updating)
  Map<String, dynamic> toMap() {
    return {
      'name': name,
    };
  }
}
