class Direction {
  int? id; // Nullable, because the ID will be auto-generated by the database
  String name;
  String place_name;

  // Constructor to create a Place object directly with a name
  Direction({required this.name, required this.place_name});
  // Constructor to create a Place from a Map (e.g., from a database row)
  Direction.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        place_name = map['place_name'];

  // Method to convert a City object back to a Map (useful for inserting/updating)
  Map<String, dynamic> toMap() {
    return {'name': name, 'place_name': place_name};
  }
}
