class Linknaka {
  int? id; // Nullable, because the ID will be auto-generated by the database
  String name;
  int placeName; // Instead of place_id, we now store place_name as a string

  // Constructor
  Linknaka({required this.name, required this.placeName});

  // Constructor to create a Naka object from a Map (e.g., from a database row)
  Linknaka.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        placeName = map['place_name'];

  // Method to convert a Naka object back to a Map (useful for inserting/updating)
  Map<String, dynamic> toMap() {
    return {'name': name, 'place_name': placeName};
  }
}
