class Place {
  int? id; // Nullable, because the ID will be auto-generated by the database
  String name;
  int city_id;

  // Constructor to create a Place object directly with a name
  Place({required this.name, required this.city_id});
  // Constructor to create a Place from a Map (e.g., from a database row)
  Place.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        name = map['name'],
        city_id = map['city_id'];

  // Method to convert a City object back to a Map (useful for inserting/updating)
  Map<String, dynamic> toMap() {
    return {'name': name, 'city_id': city_id};
  }
}
