class User {
  int? id; // Nullable, because the ID will be auto-generated by the database
  String title;
  int member;
  String comment;

  // Constructor to create a City object directly with a name
  User({required this.title, required this.member, required this.comment});
  // Constructor to create a City from a Map (e.g., from a database row)
  User.fromMap(Map<String, dynamic> map)
      : id = map['id'],
        title = map['title'],
        member = map['member'],
        comment = map['comment'];

  // Method to convert a City object back to a Map (useful for inserting/updating)
  Map<String, dynamic> toMap() {
    return {
      'title': this.title,
      'id': this.id,
      'member': this.member,
      'comment': this.comment
    };
  }
}
